generate_home_mgt_lists_task:
  description: >
    Help create a structured to-do lists based on user input: {user_input}
    They can include sections for weekly, monthly, and seasonal tasks
  expected_output: >
     A markdown-formatted list of home tasks saved to `home_tasks.md`, with sections for weekly, monthly, and seasonal tasks.
  agent: list_manager
  output_file: "home_tasks.md"

