generate_home_mgt_lists_task:
  description: >
    Create weekly, monthly, and seasonal home management lists.
    Ensure the lists include cleaning, maintenance, and recurring family activities.
    Categorize tasks based on urgency and importance.
  expected_output: >
    A structured list of tasks grouped into weekly, monthly, and seasonal categories.
  agent: list_manager

